In [1]:
import numpy as np

In [2]:
def transform(a,b):
    return a + b/60
def transform2(x):
    return (x//1,np.round((x-x//1)*60))

In [3]:
k1_theta1 = np.array([transform(211,8),transform(334,24),transform(95,37)])
k1_theta2 = np.array([transform(31,4),transform(154,23),transform(277,36)])
k1_theta1p = np.array([transform(92,8),transform(213,20),transform(334,2)])
k1_theta2p = np.array([transform(272,10),transform(33,24),transform(153,57)])

In [4]:
k2_theta1 = np.array([transform(280,36),transform(137,30),transform(86,31)])
k2_theta2 = np.array([transform(100,40),transform(317,30),transform(266,30)])
k2_theta1p = np.array([transform(219,0),transform(75,4),transform(24,42)])
k2_theta2p = np.array([transform(39,1),transform(255,10),transform(204,41)])

In [5]:
print(np.abs(k1_theta1 - k1_theta2))
print(np.abs(k1_theta1p - k1_theta2p))
print(np.abs(k2_theta1 - k2_theta2))
print(np.abs(k2_theta1p - k2_theta2p))

print(np.abs(k1_theta1p - k1_theta1))
print(np.abs(k1_theta2p - k1_theta2))
print(np.abs(k2_theta1p - k2_theta1))
print(np.abs(k2_theta2p - k2_theta2))

[180.06666667 180.01666667 181.98333333]
[180.03333333 179.93333333 180.08333333]
[179.93333333 180.         179.98333333]
[179.98333333 180.1        179.98333333]
[119.         121.06666667 238.41666667]
[241.1        120.98333333 123.65      ]
[61.6        62.43333333 61.81666667]
[61.65       62.33333333 61.81666667]


In [29]:
test_data = np.array([np.abs(k1_theta1 - k1_theta2),
np.abs(k1_theta1p - k1_theta2p),
np.abs(k2_theta1 - k2_theta2),
np.abs(k2_theta1p - k2_theta2p)])

In [15]:
tmp1 = np.abs(k1_theta1p - k1_theta1)
tmp1[2] = 360 - tmp1[2]
tmp2 = np.abs(k1_theta2p - k1_theta2)
tmp2[0] = 360 - tmp2[0]
test_data = (tmp1 + tmp2)/2

In [22]:
tmp1 = np.abs(k2_theta1p - k2_theta1)
# tmp1[2] = 360 - tmp1[2]
tmp2 = np.abs(k2_theta2p - k2_theta2)
# tmp2[0] = 360 - tmp2[0]
test_data = (tmp1 + tmp2)/2

In [23]:
print(test_data)

[61.625      62.38333333 61.81666667]


In [24]:
np.std(test_data,ddof=1)

0.3943172721440313

In [9]:
transform2(np.std(test_data,ddof=1))

(1.0, 50.0)

In [13]:
np.average(test_data,axis=0)

61.94166666666667

In [12]:
import math

In [14]:
math.sin((62 + 60)/360*math.pi) / math.sin((62)/360*math.pi)

1.6981651449596977

In [25]:
0.3943172721440313/math.sqrt(3)

0.2276591832184754

In [19]:
1/60/math.sqrt(3)

0.009622504486493762

In [26]:
math.sqrt((4.3*0.227)**2 + (1.96 * 0.002)**2)

0.9761078712929222

In [21]:
0.45 * 60

27.0

In [27]:
1.698 * 0.0034

0.005773199999999999